backend:
  name: github
  repo: james-ciclitira/London-working # Path to your Github repository
  branch: master # Branch to update

media_folder: "src/img"
public_folder: "/public/static"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "type", name: "Location type", widget: "string"}
      - {label: "wifi", name: "Wifi Speed", widget: "string"}
      - {label: "password", name: "Wifi Password", widget: "string"}
      - {label: "hours", name: "Weekday opening hours", widget: "string"}
      - {label: "directions", name: "Google map directions", widget: "string"}