backend:
  name: github
  repo: james-ciclitira/London-working
  branch: master

media_folder: "images"
public_folder: "/public/static"

collections:
  - name: "blog"
    label: "Locations"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "date", name: "date", widget: "datetime"}
      - {label: "title", name: "title", widget: "string"}
      - {label: "Location type", name: "type", widget: "string"}
      - {label: "wifi upload speed", name: "upload", widget: "string"}
      - {label: "wifi download speed", name: "download", widget: "string"}
      - {label: "wifi password", name: "password", widget: "string"}
      - {label: "Weekday open hours", name: "hours", widget: "string"}
      - {label: "Google maps directions", name: "directions", widget: "string"}
      - {label: "image", name: "image", widget: "image"}