backend:
  name: github
  repo: james-ciclitira/London-working # Path to your Github repository
  branch: master # Branch to update

media_folder: "src/img"
public_folder: "/public/static"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Locations" # Used in the UI
    folder: "src/pages/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "date", name: "date", widget: "datetime"}
      - {label: "title", name: "title", widget: "string"}
      - {label: "Location type", name: "type", widget: "string"}
      - {label: "wifi speed", name: "wifi", widget: "string"}
      - {label: "wifi password", name: "password", widget: "string"}
      - {label: "Weekday open hours", name: "hours", widget: "string"}
      - {label: "Google maps directions", name: "directions", widget: "string"}